name: subtree-index

on: [push]

jobs:
  sync-downstream:

    runs-on: ubuntu-latest

    name: Update downstream infogulch/index repo

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: infogulch/index
          deploy_key: ${{ secrets.DOWNSTREAM_GITHUB_DEPLOY_KEY }}
          force: true # will force push to the downstream repository
